dataset_config:
  sgl:
      data_dir: ${env.data_dir}/datasets
      depth_first: false
      fast_read: false
      use_images: false
      use_features: true
      zoo_requirements:
      - sgl.defaults
      images:
        train:
        - sgl/defaults/images/train
        val:
        - sgl/defaults/images/val
        test:
        - sgl/defaults/images/test
      features:
        train:
        - sgl/defaults/features/train
        val:
        - sgl/defaults/features/val
        test:
        - sgl/defaults/features/test
      annotations:
        train:
        - sgl/defaults/annotations/imdb_train.npy
        val:
        - sgl/defaults/annotations/imdb_val.npy
        test:
        - sgl/defaults/annotations/imdb_test.npy
      max_features: 100
      processors:
        text_processor:
          type: vocab
          params:
            max_length: 30
            vocab:
              type: intersected
              embedding_name: glove.6B.300d
              vocab_file: sgl/defaults/extras/vocabs/vocabulary_100k.txt
            preprocessor:
              type: simple_sentence
              params: {}
        answer_processor:
          type: sgl_result
          params:
            vocab_state_file: sgl/defaults/extras/vocabs/state_gtrtr.txt
            vocab_object_file: sgl/defaults/extras/vocabs/object_gtrtr.txt
            preprocessor:
              type: simple_word
              params: {}
        context_processor:
          type: fasttext
          params:
            download_initially: false
            max_length: 50
            model_file: wiki.en.bin

      return_features_info: false
      # Return OCR information
      use_ocr: false
      # Return spatial information of OCR tokens if present
      use_ocr_info: false
