model_config:
  resnet_bert_concat:
    # Type of bert model
    bert_model_name: bert-base-uncased
    direct_features_input: false
    # Dimension of the embedding finally returned by the modal encoder
    modal_hidden_size: 512
    # Dimension of the embedding finally returned by the text encoder
    text_hidden_size: 768
    # Used when classification head is activated
    num_labels: 2
    # Number of features extracted out per image
    num_features: 1

    image_encoder:
      type: resnet34 #resnet34, resnet152
      params:
        pretrained: true
        pool_type: avg
        num_output_features: 1 
        pretrained_model: ${env:MMF_SAVE_DIR, ./pretrained_models/resnet_backbone-32.tar}

    text_encoder:
      type: transformer
      params:
        bert_model_name: bert-base-uncased
        hidden_size: 768
        num_hidden_layers: 12
        num_attention_heads: 12
        output_attentions: false
        output_hidden_states: false
        pretrained_model: false

    classifier_state:
      type: mlp
      params:
        in_dim: 1280
        out_dim: 5
        hidden_dim: 256
        num_layers: 2
        
    classifier_subject:
      type: mlp
      params:
        in_dim: 1280 
        out_dim: 35 
        hidden_dim: 256
        num_layers: 2

    classifier_object:
      type: mlp
      params:
        in_dim: 1280
        out_dim: 35
        hidden_dim: 256
        num_layers: 2
